name: "Release OSMMapCore"

on:
    push:
      tags:
        - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build-deploy-ios:
    name: "Build and Deploy iOS Release"
    runs-on: macos-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Set version variable"
        run: |
          RELEASE_VERSION=$(if [[ ${{ github.ref_type }} == "tag" ]]; then echo ${{ github.ref_name }}; else echo ${{ github.sha }}; fi)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: "set permission build.sh"
        run: chmod +x build.sh
      - name: "run build.sh"
        run: ./build.sh ${{env.RELEASE_VERSION}}

      - name: "Upload pod"
        uses: actions/upload-artifact@v2
        with:
          name: tangram-ios-${{ env.RELEASE_VERSION }}
          path: build/pod/
      - name: Install Cocoapods
        run: gem install cocoapods    
      - name: Deploy to Cocoapods
        run: |
            set -eo pipefail
            pod lib lint --allow-warnings
            pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
